//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TrigParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TrigParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ITrigParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.trigDoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigDoc([NotNull] TrigParser.TrigDocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] TrigParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.triplesOrGraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriplesOrGraph([NotNull] TrigParser.TriplesOrGraphContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.triples2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriples2([NotNull] TrigParser.Triples2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.wrappedGraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWrappedGraph([NotNull] TrigParser.WrappedGraphContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.triplesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriplesBlock([NotNull] TrigParser.TriplesBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.labelOrSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelOrSubject([NotNull] TrigParser.LabelOrSubjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] TrigParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.prefixID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixID([NotNull] TrigParser.PrefixIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase([NotNull] TrigParser.BaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion([NotNull] TrigParser.VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.versionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersionSpecifier([NotNull] TrigParser.VersionSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.sparqlPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlPrefix([NotNull] TrigParser.SparqlPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.sparqlBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlBase([NotNull] TrigParser.SparqlBaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.sparqlVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlVersion([NotNull] TrigParser.SparqlVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.triples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriples([NotNull] TrigParser.TriplesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.predicateObjectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateObjectList([NotNull] TrigParser.PredicateObjectListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectList([NotNull] TrigParser.ObjectListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.verb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVerb([NotNull] TrigParser.VerbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.subject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubject([NotNull] TrigParser.SubjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] TrigParser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] TrigParser.ObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] TrigParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.blankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlankNodePropertyList([NotNull] TrigParser.BlankNodePropertyListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollection([NotNull] TrigParser.CollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericLiteral([NotNull] TrigParser.NumericLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.rdfLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRdfLiteral([NotNull] TrigParser.RdfLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_([NotNull] TrigParser.String_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] TrigParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIri([NotNull] TrigParser.IriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.prefixedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixedName([NotNull] TrigParser.PrefixedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.blankNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlankNode([NotNull] TrigParser.BlankNodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.reifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReifier([NotNull] TrigParser.ReifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.reifiedTriple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReifiedTriple([NotNull] TrigParser.ReifiedTripleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.rtSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRtSubject([NotNull] TrigParser.RtSubjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.rtObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRtObject([NotNull] TrigParser.RtObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.tripleTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTripleTerm([NotNull] TrigParser.TripleTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.ttSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTtSubject([NotNull] TrigParser.TtSubjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.ttObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTtObject([NotNull] TrigParser.TtObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] TrigParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TrigParser.annotationBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationBlock([NotNull] TrigParser.AnnotationBlockContext context);
}
