language: csharp
mono: none
os: linux
dist: bionic
dotnet: 5.0
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test fifth.test/fifth.test.csproj
notifications:
  slack: matthews-family:PzF5BbuJiQlFsYX9iQKKTIn6
