language: csharp
mono: none
dist: bionic
sudo: required 
dotnet: 5
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test fifth.test/fifth.test.csproj
notifications:
  slack: matthews-family:PzF5BbuJiQlFsYX9iQKKTIn6
