//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FifthParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FifthParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IFifthParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.namespace_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_decl([NotNull] FifthParser.Namespace_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.import_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_decl([NotNull] FifthParser.Import_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.qualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_name([NotNull] FifthParser.Qualified_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.plain_paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlain_paramdecl([NotNull] FifthParser.Plain_paramdeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructor_declaration([NotNull] FifthParser.Constructor_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.base_constructor_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_constructor_call([NotNull] FifthParser.Base_constructor_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_list([NotNull] FifthParser.Type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter([NotNull] FifthParser.Type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list([NotNull] FifthParser.Type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.constraint_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint_clause([NotNull] FifthParser.Constraint_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.constraint_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint_list([NotNull] FifthParser.Constraint_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_constraint([NotNull] FifthParser.Type_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] FifthParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_statement([NotNull] FifthParser.Assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] FifthParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] FifthParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] FifthParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] FifthParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_statement([NotNull] FifthParser.With_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTry_statement([NotNull] FifthParser.Try_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatch_clause([NotNull] FifthParser.Catch_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.finally_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_clause([NotNull] FifthParser.Finally_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrow_statement([NotNull] FifthParser.Throw_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_body([NotNull] FifthParser.List_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>generic_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_type_spec([NotNull] FifthParser.Generic_type_specContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>array_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_spec([NotNull] FifthParser.Array_type_specContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>base_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_type_spec([NotNull] FifthParser.Base_type_specContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_func_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_func_spec([NotNull] FifthParser.Type_func_specContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>list_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_type_spec([NotNull] FifthParser.List_type_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_type_spec([NotNull] FifthParser.Function_type_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_query_application</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_query_application([NotNull] FifthParser.Exp_query_applicationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_index</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_index([NotNull] FifthParser.Exp_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_throw</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_throw([NotNull] FifthParser.Exp_throwContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_expression([NotNull] FifthParser.Lambda_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.tripleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTripleExpression([NotNull] FifthParser.TripleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>triple_literal</c>
	/// labeled alternative in <see cref="FifthParser.tripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriple_literal([NotNull] FifthParser.Triple_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>triple_malformed_missingObject</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriple_malformed_missingObject([NotNull] FifthParser.Triple_malformed_missingObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>triple_malformed_trailingComma</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriple_malformed_trailingComma([NotNull] FifthParser.Triple_malformed_trailingCommaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>triple_malformed_tooMany</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriple_malformed_tooMany([NotNull] FifthParser.Triple_malformed_tooManyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.tripleObjectTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTripleObjectTerm([NotNull] FifthParser.TripleObjectTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.prefixedIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixedIri([NotNull] FifthParser.PrefixedIriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.tripleIriRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTripleIriRef([NotNull] FifthParser.TripleIriRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] FifthParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.trigLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigLiteral([NotNull] FifthParser.TrigLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.trigLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigLiteralContent([NotNull] FifthParser.TrigLiteralContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.trigInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigInterpolation([NotNull] FifthParser.TrigInterpolationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.sparqlLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlLiteral([NotNull] FifthParser.SparqlLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.sparqlLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlLiteralContent([NotNull] FifthParser.SparqlLiteralContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.sparqlInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSparqlInterpolation([NotNull] FifthParser.SparqlInterpolationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_plain([NotNull] FifthParser.Str_plainContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIri([NotNull] FifthParser.IriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.graphDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphDeclaration([NotNull] FifthParser.GraphDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.colon_graph_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColon_graph_decl([NotNull] FifthParser.Colon_graph_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.alias_scope_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_scope_ref([NotNull] FifthParser.Alias_scope_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.colon_store_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColon_store_decl([NotNull] FifthParser.Colon_store_declContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>store_sparql</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStore_sparql([NotNull] FifthParser.Store_sparqlContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>store_func_call</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStore_func_call([NotNull] FifthParser.Store_func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.store_arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStore_arg_list([NotNull] FifthParser.Store_arg_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.store_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStore_arg([NotNull] FifthParser.Store_argContext context);
}
