//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FifthParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FifthParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IFifthParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.namespace_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace_decl([NotNull] FifthParser.Namespace_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.namespace_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace_decl([NotNull] FifthParser.Namespace_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.import_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_decl([NotNull] FifthParser.Import_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.import_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_decl([NotNull] FifthParser.Import_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualified_name([NotNull] FifthParser.Qualified_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualified_name([NotNull] FifthParser.Qualified_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.plain_paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlain_paramdecl([NotNull] FifthParser.Plain_paramdeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.plain_paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlain_paramdecl([NotNull] FifthParser.Plain_paramdeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructor_declaration([NotNull] FifthParser.Constructor_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.constructor_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructor_declaration([NotNull] FifthParser.Constructor_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.base_constructor_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_constructor_call([NotNull] FifthParser.Base_constructor_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.base_constructor_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_constructor_call([NotNull] FifthParser.Base_constructor_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_parameter_list([NotNull] FifthParser.Type_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_parameter_list([NotNull] FifthParser.Type_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_parameter([NotNull] FifthParser.Type_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_parameter([NotNull] FifthParser.Type_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_argument_list([NotNull] FifthParser.Type_argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_argument_list([NotNull] FifthParser.Type_argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.constraint_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint_clause([NotNull] FifthParser.Constraint_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.constraint_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint_clause([NotNull] FifthParser.Constraint_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.constraint_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint_list([NotNull] FifthParser.Constraint_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.constraint_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint_list([NotNull] FifthParser.Constraint_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_constraint([NotNull] FifthParser.Type_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_constraint([NotNull] FifthParser.Type_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] FifthParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] FifthParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_statement([NotNull] FifthParser.Assignment_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_statement([NotNull] FifthParser.Assignment_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_statement([NotNull] FifthParser.Expression_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_statement([NotNull] FifthParser.Expression_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] FifthParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] FifthParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] FifthParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] FifthParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] FifthParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] FifthParser.While_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_statement([NotNull] FifthParser.With_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_statement([NotNull] FifthParser.With_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_statement([NotNull] FifthParser.Try_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.try_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_statement([NotNull] FifthParser.Try_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatch_clause([NotNull] FifthParser.Catch_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.catch_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatch_clause([NotNull] FifthParser.Catch_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.finally_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinally_clause([NotNull] FifthParser.Finally_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.finally_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinally_clause([NotNull] FifthParser.Finally_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrow_statement([NotNull] FifthParser.Throw_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.throw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrow_statement([NotNull] FifthParser.Throw_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_body([NotNull] FifthParser.List_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_body([NotNull] FifthParser.List_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>generic_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_type_spec([NotNull] FifthParser.Generic_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>generic_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_type_spec([NotNull] FifthParser.Generic_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>array_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_type_spec([NotNull] FifthParser.Array_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>array_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_type_spec([NotNull] FifthParser.Array_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>base_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_type_spec([NotNull] FifthParser.Base_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>base_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_type_spec([NotNull] FifthParser.Base_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>type_func_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_func_spec([NotNull] FifthParser.Type_func_specContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>type_func_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_func_spec([NotNull] FifthParser.Type_func_specContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>list_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_type_spec([NotNull] FifthParser.List_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>list_type_spec</c>
	/// labeled alternative in <see cref="FifthParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_type_spec([NotNull] FifthParser.List_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type_spec([NotNull] FifthParser.Function_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type_spec([NotNull] FifthParser.Function_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_query_application</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_query_application([NotNull] FifthParser.Exp_query_applicationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_query_application</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_query_application([NotNull] FifthParser.Exp_query_applicationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_index</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_index([NotNull] FifthParser.Exp_indexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_index</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_index([NotNull] FifthParser.Exp_indexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_throw</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_throw([NotNull] FifthParser.Exp_throwContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_throw</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_throw([NotNull] FifthParser.Exp_throwContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_expression([NotNull] FifthParser.Lambda_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.lambda_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_expression([NotNull] FifthParser.Lambda_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.tripleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTripleExpression([NotNull] FifthParser.TripleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.tripleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTripleExpression([NotNull] FifthParser.TripleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.primitiveLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>triple_literal</c>
	/// labeled alternative in <see cref="FifthParser.tripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriple_literal([NotNull] FifthParser.Triple_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>triple_literal</c>
	/// labeled alternative in <see cref="FifthParser.tripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriple_literal([NotNull] FifthParser.Triple_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>triple_malformed_missingObject</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriple_malformed_missingObject([NotNull] FifthParser.Triple_malformed_missingObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>triple_malformed_missingObject</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriple_malformed_missingObject([NotNull] FifthParser.Triple_malformed_missingObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>triple_malformed_trailingComma</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriple_malformed_trailingComma([NotNull] FifthParser.Triple_malformed_trailingCommaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>triple_malformed_trailingComma</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriple_malformed_trailingComma([NotNull] FifthParser.Triple_malformed_trailingCommaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>triple_malformed_tooMany</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriple_malformed_tooMany([NotNull] FifthParser.Triple_malformed_tooManyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>triple_malformed_tooMany</c>
	/// labeled alternative in <see cref="FifthParser.malformedTripleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriple_malformed_tooMany([NotNull] FifthParser.Triple_malformed_tooManyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.tripleObjectTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTripleObjectTerm([NotNull] FifthParser.TripleObjectTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.tripleObjectTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTripleObjectTerm([NotNull] FifthParser.TripleObjectTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.prefixedIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixedIri([NotNull] FifthParser.PrefixedIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.prefixedIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixedIri([NotNull] FifthParser.PrefixedIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.tripleIriRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTripleIriRef([NotNull] FifthParser.TripleIriRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.tripleIriRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTripleIriRef([NotNull] FifthParser.TripleIriRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] FifthParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] FifthParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.trigLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigLiteral([NotNull] FifthParser.TrigLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.trigLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigLiteral([NotNull] FifthParser.TrigLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.trigLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigLiteralContent([NotNull] FifthParser.TrigLiteralContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.trigLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigLiteralContent([NotNull] FifthParser.TrigLiteralContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.trigInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigInterpolation([NotNull] FifthParser.TrigInterpolationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.trigInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigInterpolation([NotNull] FifthParser.TrigInterpolationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.sparqlLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSparqlLiteral([NotNull] FifthParser.SparqlLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.sparqlLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSparqlLiteral([NotNull] FifthParser.SparqlLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.sparqlLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSparqlLiteralContent([NotNull] FifthParser.SparqlLiteralContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.sparqlLiteralContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSparqlLiteralContent([NotNull] FifthParser.SparqlLiteralContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.sparqlInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSparqlInterpolation([NotNull] FifthParser.SparqlInterpolationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.sparqlInterpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSparqlInterpolation([NotNull] FifthParser.SparqlInterpolationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr_plain([NotNull] FifthParser.Str_plainContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr_plain([NotNull] FifthParser.Str_plainContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIri([NotNull] FifthParser.IriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIri([NotNull] FifthParser.IriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.graphDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphDeclaration([NotNull] FifthParser.GraphDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.graphDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphDeclaration([NotNull] FifthParser.GraphDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.colon_graph_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColon_graph_decl([NotNull] FifthParser.Colon_graph_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.colon_graph_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColon_graph_decl([NotNull] FifthParser.Colon_graph_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias_scope_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias_scope_ref([NotNull] FifthParser.Alias_scope_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias_scope_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias_scope_ref([NotNull] FifthParser.Alias_scope_refContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.colon_store_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColon_store_decl([NotNull] FifthParser.Colon_store_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.colon_store_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColon_store_decl([NotNull] FifthParser.Colon_store_declContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>store_sparql</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStore_sparql([NotNull] FifthParser.Store_sparqlContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>store_sparql</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStore_sparql([NotNull] FifthParser.Store_sparqlContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>store_func_call</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStore_func_call([NotNull] FifthParser.Store_func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>store_func_call</c>
	/// labeled alternative in <see cref="FifthParser.store_creation_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStore_func_call([NotNull] FifthParser.Store_func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.store_arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStore_arg_list([NotNull] FifthParser.Store_arg_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.store_arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStore_arg_list([NotNull] FifthParser.Store_arg_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.store_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStore_arg([NotNull] FifthParser.Store_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.store_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStore_arg([NotNull] FifthParser.Store_argContext context);
}
