//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from fifth.parser/grammar/Fifth.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FifthParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IFifthListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] FifthParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] FifthParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_name([NotNull] FifthParser.Module_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_name([NotNull] FifthParser.Module_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_initialiser"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_initialiser([NotNull] FifthParser.Type_initialiserContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_initialiser"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_initialiser([NotNull] FifthParser.Type_initialiserContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_property_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_property_init([NotNull] FifthParser.Type_property_initContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_property_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_property_init([NotNull] FifthParser.Type_property_initContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.formal_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_parameters([NotNull] FifthParser.Formal_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.formal_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_parameters([NotNull] FifthParser.Formal_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_args([NotNull] FifthParser.Function_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_args([NotNull] FifthParser.Function_argsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declaration([NotNull] FifthParser.Parameter_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declaration([NotNull] FifthParser.Parameter_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_type([NotNull] FifthParser.Parameter_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_type([NotNull] FifthParser.Parameter_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_name([NotNull] FifthParser.Parameter_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_name([NotNull] FifthParser.Parameter_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type([NotNull] FifthParser.Function_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type([NotNull] FifthParser.Function_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SIfElse</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSIfElse([NotNull] FifthParser.SIfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SIfElse</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSIfElse([NotNull] FifthParser.SIfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SWhile</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSWhile([NotNull] FifthParser.SWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SWhile</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSWhile([NotNull] FifthParser.SWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SWith</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSWith([NotNull] FifthParser.SWithContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SWith</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSWith([NotNull] FifthParser.SWithContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SVarDecl</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSVarDecl([NotNull] FifthParser.SVarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SVarDecl</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSVarDecl([NotNull] FifthParser.SVarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SAssignment</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSAssignment([NotNull] FifthParser.SAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SAssignment</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSAssignment([NotNull] FifthParser.SAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SReturn</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSReturn([NotNull] FifthParser.SReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SReturn</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSReturn([NotNull] FifthParser.SReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SBareExpression</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSBareExpression([NotNull] FifthParser.SBareExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SBareExpression</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSBareExpression([NotNull] FifthParser.SBareExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] FifthParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] FifthParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EFuncCall</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEFuncCall([NotNull] FifthParser.EFuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EFuncCall</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEFuncCall([NotNull] FifthParser.EFuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EBool</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEBool([NotNull] FifthParser.EBoolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EBool</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEBool([NotNull] FifthParser.EBoolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EVarname</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEVarname([NotNull] FifthParser.EVarnameContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EVarname</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEVarname([NotNull] FifthParser.EVarnameContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EArithNegation</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEArithNegation([NotNull] FifthParser.EArithNegationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EArithNegation</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEArithNegation([NotNull] FifthParser.EArithNegationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ETypeCast</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterETypeCast([NotNull] FifthParser.ETypeCastContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ETypeCast</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitETypeCast([NotNull] FifthParser.ETypeCastContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEInt([NotNull] FifthParser.EIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EInt</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEInt([NotNull] FifthParser.EIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ELT</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterELT([NotNull] FifthParser.ELTContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ELT</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitELT([NotNull] FifthParser.ELTContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EDiv</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEDiv([NotNull] FifthParser.EDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EDiv</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEDiv([NotNull] FifthParser.EDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EGEQ</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEGEQ([NotNull] FifthParser.EGEQContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EGEQ</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEGEQ([NotNull] FifthParser.EGEQContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ELogicNegation</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterELogicNegation([NotNull] FifthParser.ELogicNegationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ELogicNegation</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitELogicNegation([NotNull] FifthParser.ELogicNegationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAnd([NotNull] FifthParser.EAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAnd</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAnd([NotNull] FifthParser.EAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EList</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEList([NotNull] FifthParser.EListContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EList</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEList([NotNull] FifthParser.EListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EGT</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEGT([NotNull] FifthParser.EGTContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EGT</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEGT([NotNull] FifthParser.EGTContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ELEQ</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterELEQ([NotNull] FifthParser.ELEQContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ELEQ</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitELEQ([NotNull] FifthParser.ELEQContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ETypeCreateInst</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterETypeCreateInst([NotNull] FifthParser.ETypeCreateInstContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ETypeCreateInst</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitETypeCreateInst([NotNull] FifthParser.ETypeCreateInstContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEParen([NotNull] FifthParser.EParenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EParen</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEParen([NotNull] FifthParser.EParenContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ESub</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterESub([NotNull] FifthParser.ESubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ESub</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitESub([NotNull] FifthParser.ESubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EDouble</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEDouble([NotNull] FifthParser.EDoubleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EDouble</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEDouble([NotNull] FifthParser.EDoubleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EAdd</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEAdd([NotNull] FifthParser.EAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EAdd</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEAdd([NotNull] FifthParser.EAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EString</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEString([NotNull] FifthParser.EStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EString</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEString([NotNull] FifthParser.EStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EMul</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEMul([NotNull] FifthParser.EMulContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EMul</c>
	/// labeled alternative in <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEMul([NotNull] FifthParser.EMulContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIri([NotNull] FifthParser.IriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIri([NotNull] FifthParser.IriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qNameIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQNameIri([NotNull] FifthParser.QNameIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qNameIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQNameIri([NotNull] FifthParser.QNameIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.iri_query_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIri_query_param([NotNull] FifthParser.Iri_query_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.iri_query_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIri_query_param([NotNull] FifthParser.Iri_query_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_type_signature([NotNull] FifthParser.List_type_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_type_signature([NotNull] FifthParser.List_type_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListLiteral([NotNull] FifthParser.EListLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListLiteral([NotNull] FifthParser.EListLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListComprehension([NotNull] FifthParser.EListComprehensionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListComprehension([NotNull] FifthParser.EListComprehensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context);
}
