//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from src/fifth.parser/Parser/grammar/FifthParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FifthParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IFifthParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] FifthParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] FifthParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_list([NotNull] FifthParser.Exp_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_list([NotNull] FifthParser.Exp_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.formal_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_parameters([NotNull] FifthParser.Formal_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.formal_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_parameters([NotNull] FifthParser.Formal_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_args([NotNull] FifthParser.Function_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_args([NotNull] FifthParser.Function_argsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] FifthParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] FifthParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declaration([NotNull] FifthParser.Parameter_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declaration([NotNull] FifthParser.Parameter_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_type([NotNull] FifthParser.Parameter_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_type([NotNull] FifthParser.Parameter_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_name([NotNull] FifthParser.Parameter_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_name([NotNull] FifthParser.Parameter_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qvarname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQvarname([NotNull] FifthParser.QvarnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qvarname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQvarname([NotNull] FifthParser.QvarnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_initialiser"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_initialiser([NotNull] FifthParser.Type_initialiserContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_initialiser"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_initialiser([NotNull] FifthParser.Type_initialiserContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_property_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_property_init([NotNull] FifthParser.Type_property_initContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_property_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_property_init([NotNull] FifthParser.Type_property_initContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] FifthParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] FifthParser.VariableContext context);
}
