//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SparqlParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SparqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISparqlParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.queryUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQueryUnit([NotNull] SparqlParser.QueryUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.queryUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQueryUnit([NotNull] SparqlParser.QueryUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] SparqlParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] SparqlParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.prologue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrologue([NotNull] SparqlParser.PrologueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.prologue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrologue([NotNull] SparqlParser.PrologueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.baseDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseDecl([NotNull] SparqlParser.BaseDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.baseDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseDecl([NotNull] SparqlParser.BaseDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.prefixDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixDecl([NotNull] SparqlParser.PrefixDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.prefixDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixDecl([NotNull] SparqlParser.PrefixDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.selectQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectQuery([NotNull] SparqlParser.SelectQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.selectQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectQuery([NotNull] SparqlParser.SelectQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.subSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubSelect([NotNull] SparqlParser.SubSelectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.subSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubSelect([NotNull] SparqlParser.SubSelectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectClause([NotNull] SparqlParser.SelectClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.selectClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectClause([NotNull] SparqlParser.SelectClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.varOrProjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrProjection([NotNull] SparqlParser.VarOrProjectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.varOrProjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrProjection([NotNull] SparqlParser.VarOrProjectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.constructQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructQuery([NotNull] SparqlParser.ConstructQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.constructQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructQuery([NotNull] SparqlParser.ConstructQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.describeQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescribeQuery([NotNull] SparqlParser.DescribeQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.describeQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescribeQuery([NotNull] SparqlParser.DescribeQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.askQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAskQuery([NotNull] SparqlParser.AskQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.askQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAskQuery([NotNull] SparqlParser.AskQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetClause([NotNull] SparqlParser.DatasetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetClause([NotNull] SparqlParser.DatasetClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.defaultGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultGraphClause([NotNull] SparqlParser.DefaultGraphClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.defaultGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultGraphClause([NotNull] SparqlParser.DefaultGraphClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.namedGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedGraphClause([NotNull] SparqlParser.NamedGraphClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.namedGraphClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedGraphClause([NotNull] SparqlParser.NamedGraphClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceSelector([NotNull] SparqlParser.SourceSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceSelector([NotNull] SparqlParser.SourceSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhereClause([NotNull] SparqlParser.WhereClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.whereClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhereClause([NotNull] SparqlParser.WhereClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.solutionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSolutionModifier([NotNull] SparqlParser.SolutionModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.solutionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSolutionModifier([NotNull] SparqlParser.SolutionModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.groupClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupClause([NotNull] SparqlParser.GroupClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.groupClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupClause([NotNull] SparqlParser.GroupClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.groupCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupCondition([NotNull] SparqlParser.GroupConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.groupCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupCondition([NotNull] SparqlParser.GroupConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingClause([NotNull] SparqlParser.HavingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingClause([NotNull] SparqlParser.HavingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.havingCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingCondition([NotNull] SparqlParser.HavingConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.havingCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingCondition([NotNull] SparqlParser.HavingConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderClause([NotNull] SparqlParser.OrderClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderClause([NotNull] SparqlParser.OrderClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.orderCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderCondition([NotNull] SparqlParser.OrderConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.orderCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderCondition([NotNull] SparqlParser.OrderConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.limitOffsetClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitOffsetClauses([NotNull] SparqlParser.LimitOffsetClausesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.limitOffsetClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitOffsetClauses([NotNull] SparqlParser.LimitOffsetClausesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.limitClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitClause([NotNull] SparqlParser.LimitClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.limitClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitClause([NotNull] SparqlParser.LimitClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.offsetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffsetClause([NotNull] SparqlParser.OffsetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.offsetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffsetClause([NotNull] SparqlParser.OffsetClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.valuesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValuesClause([NotNull] SparqlParser.ValuesClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.valuesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValuesClause([NotNull] SparqlParser.ValuesClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.groupGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupGraphPattern([NotNull] SparqlParser.GroupGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.groupGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupGraphPattern([NotNull] SparqlParser.GroupGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.groupGraphPatternSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupGraphPatternSub([NotNull] SparqlParser.GroupGraphPatternSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.groupGraphPatternSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupGraphPatternSub([NotNull] SparqlParser.GroupGraphPatternSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesBlock([NotNull] SparqlParser.TriplesBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesBlock([NotNull] SparqlParser.TriplesBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.graphPatternNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphPatternNotTriples([NotNull] SparqlParser.GraphPatternNotTriplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.graphPatternNotTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphPatternNotTriples([NotNull] SparqlParser.GraphPatternNotTriplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.optionalGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalGraphPattern([NotNull] SparqlParser.OptionalGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.optionalGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalGraphPattern([NotNull] SparqlParser.OptionalGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.graphGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphGraphPattern([NotNull] SparqlParser.GraphGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.graphGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphGraphPattern([NotNull] SparqlParser.GraphGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.serviceGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterServiceGraphPattern([NotNull] SparqlParser.ServiceGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.serviceGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitServiceGraphPattern([NotNull] SparqlParser.ServiceGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBind([NotNull] SparqlParser.BindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.bind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBind([NotNull] SparqlParser.BindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.inlineData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineData([NotNull] SparqlParser.InlineDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.inlineData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineData([NotNull] SparqlParser.InlineDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataBlock([NotNull] SparqlParser.DataBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataBlock([NotNull] SparqlParser.DataBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.inlineDataOneVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineDataOneVar([NotNull] SparqlParser.InlineDataOneVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.inlineDataOneVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineDataOneVar([NotNull] SparqlParser.InlineDataOneVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.inlineDataFull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineDataFull([NotNull] SparqlParser.InlineDataFullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.inlineDataFull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineDataFull([NotNull] SparqlParser.InlineDataFullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataBlockValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataBlockValue([NotNull] SparqlParser.DataBlockValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataBlockValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataBlockValue([NotNull] SparqlParser.DataBlockValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.minusGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinusGraphPattern([NotNull] SparqlParser.MinusGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.minusGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinusGraphPattern([NotNull] SparqlParser.MinusGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.groupOrUnionGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupOrUnionGraphPattern([NotNull] SparqlParser.GroupOrUnionGraphPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.groupOrUnionGraphPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupOrUnionGraphPattern([NotNull] SparqlParser.GroupOrUnionGraphPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter([NotNull] SparqlParser.FilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter([NotNull] SparqlParser.FilterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] SparqlParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] SparqlParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SparqlParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SparqlParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] SparqlParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] SparqlParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] SparqlParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] SparqlParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.constructTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructTemplate([NotNull] SparqlParser.ConstructTemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.constructTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructTemplate([NotNull] SparqlParser.ConstructTemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.constructTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructTriples([NotNull] SparqlParser.ConstructTriplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.constructTriples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructTriples([NotNull] SparqlParser.ConstructTriplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesSameSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesSameSubject([NotNull] SparqlParser.TriplesSameSubjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesSameSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesSameSubject([NotNull] SparqlParser.TriplesSameSubjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.propertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyList([NotNull] SparqlParser.PropertyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.propertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyList([NotNull] SparqlParser.PropertyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.propertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListNotEmpty([NotNull] SparqlParser.PropertyListNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.propertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListNotEmpty([NotNull] SparqlParser.PropertyListNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.verb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerb([NotNull] SparqlParser.VerbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.verb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerb([NotNull] SparqlParser.VerbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectList([NotNull] SparqlParser.ObjectListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.objectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectList([NotNull] SparqlParser.ObjectListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] SparqlParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] SparqlParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesSameSubjectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesSameSubjectPath([NotNull] SparqlParser.TriplesSameSubjectPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesSameSubjectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesSameSubjectPath([NotNull] SparqlParser.TriplesSameSubjectPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.propertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListPath([NotNull] SparqlParser.PropertyListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.propertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListPath([NotNull] SparqlParser.PropertyListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.propertyListPathNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyListPathNotEmpty([NotNull] SparqlParser.PropertyListPathNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.propertyListPathNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyListPathNotEmpty([NotNull] SparqlParser.PropertyListPathNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.verbPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerbPath([NotNull] SparqlParser.VerbPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.verbPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerbPath([NotNull] SparqlParser.VerbPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.verbSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVerbSimple([NotNull] SparqlParser.VerbSimpleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.verbSimple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVerbSimple([NotNull] SparqlParser.VerbSimpleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.objectListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectListPath([NotNull] SparqlParser.ObjectListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.objectListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectListPath([NotNull] SparqlParser.ObjectListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.objectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectPath([NotNull] SparqlParser.ObjectPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.objectPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectPath([NotNull] SparqlParser.ObjectPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] SparqlParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] SparqlParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathAlternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathAlternative([NotNull] SparqlParser.PathAlternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathAlternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathAlternative([NotNull] SparqlParser.PathAlternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathSequence([NotNull] SparqlParser.PathSequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathSequence([NotNull] SparqlParser.PathSequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathElt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathElt([NotNull] SparqlParser.PathEltContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathElt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathElt([NotNull] SparqlParser.PathEltContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathEltOrInverse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathEltOrInverse([NotNull] SparqlParser.PathEltOrInverseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathEltOrInverse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathEltOrInverse([NotNull] SparqlParser.PathEltOrInverseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathMod([NotNull] SparqlParser.PathModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathMod([NotNull] SparqlParser.PathModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathPrimary([NotNull] SparqlParser.PathPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathPrimary([NotNull] SparqlParser.PathPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathNegatedPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathNegatedPropertySet([NotNull] SparqlParser.PathNegatedPropertySetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathNegatedPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathNegatedPropertySet([NotNull] SparqlParser.PathNegatedPropertySetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.pathOneInPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathOneInPropertySet([NotNull] SparqlParser.PathOneInPropertySetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.pathOneInPropertySet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathOneInPropertySet([NotNull] SparqlParser.PathOneInPropertySetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] SparqlParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] SparqlParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesNode([NotNull] SparqlParser.TriplesNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesNode([NotNull] SparqlParser.TriplesNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.blankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNodePropertyList([NotNull] SparqlParser.BlankNodePropertyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.blankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNodePropertyList([NotNull] SparqlParser.BlankNodePropertyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesNodePath([NotNull] SparqlParser.TriplesNodePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesNodePath([NotNull] SparqlParser.TriplesNodePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.blankNodePropertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNodePropertyListPath([NotNull] SparqlParser.BlankNodePropertyListPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.blankNodePropertyListPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNodePropertyListPath([NotNull] SparqlParser.BlankNodePropertyListPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollection([NotNull] SparqlParser.CollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollection([NotNull] SparqlParser.CollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.collectionPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionPath([NotNull] SparqlParser.CollectionPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.collectionPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionPath([NotNull] SparqlParser.CollectionPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.graphNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphNode([NotNull] SparqlParser.GraphNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.graphNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphNode([NotNull] SparqlParser.GraphNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.graphNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphNodePath([NotNull] SparqlParser.GraphNodePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.graphNodePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphNodePath([NotNull] SparqlParser.GraphNodePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.varOrTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrTerm([NotNull] SparqlParser.VarOrTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.varOrTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrTerm([NotNull] SparqlParser.VarOrTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.varOrIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrIri([NotNull] SparqlParser.VarOrIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.varOrIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrIri([NotNull] SparqlParser.VarOrIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] SparqlParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] SparqlParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.graphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphTerm([NotNull] SparqlParser.GraphTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.graphTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphTerm([NotNull] SparqlParser.GraphTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.tripleTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTripleTerm([NotNull] SparqlParser.TripleTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.tripleTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTripleTerm([NotNull] SparqlParser.TripleTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataValueTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataValueTerm([NotNull] SparqlParser.DataValueTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataValueTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataValueTerm([NotNull] SparqlParser.DataValueTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataCollection([NotNull] SparqlParser.DataCollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataCollection([NotNull] SparqlParser.DataCollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataBlankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataBlankNodePropertyList([NotNull] SparqlParser.DataBlankNodePropertyListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataBlankNodePropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataBlankNodePropertyList([NotNull] SparqlParser.DataBlankNodePropertyListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataPropertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataPropertyListNotEmpty([NotNull] SparqlParser.DataPropertyListNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataPropertyListNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataPropertyListNotEmpty([NotNull] SparqlParser.DataPropertyListNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.dataObjectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataObjectList([NotNull] SparqlParser.DataObjectListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.dataObjectList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataObjectList([NotNull] SparqlParser.DataObjectListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SparqlParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SparqlParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalOrExpression([NotNull] SparqlParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.conditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalOrExpression([NotNull] SparqlParser.ConditionalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalAndExpression([NotNull] SparqlParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.conditionalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalAndExpression([NotNull] SparqlParser.ConditionalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.valueLogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueLogical([NotNull] SparqlParser.ValueLogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.valueLogical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueLogical([NotNull] SparqlParser.ValueLogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] SparqlParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] SparqlParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.numericExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericExpression([NotNull] SparqlParser.NumericExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.numericExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericExpression([NotNull] SparqlParser.NumericExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] SparqlParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] SparqlParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] SparqlParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] SparqlParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] SparqlParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] SparqlParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] SparqlParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] SparqlParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.brackettedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrackettedExpression([NotNull] SparqlParser.BrackettedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.brackettedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrackettedExpression([NotNull] SparqlParser.BrackettedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.builtInCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInCall([NotNull] SparqlParser.BuiltInCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.builtInCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInCall([NotNull] SparqlParser.BuiltInCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.regexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexExpression([NotNull] SparqlParser.RegexExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.regexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexExpression([NotNull] SparqlParser.RegexExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.substringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubstringExpression([NotNull] SparqlParser.SubstringExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.substringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubstringExpression([NotNull] SparqlParser.SubstringExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.strReplaceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrReplaceExpression([NotNull] SparqlParser.StrReplaceExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.strReplaceExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrReplaceExpression([NotNull] SparqlParser.StrReplaceExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.existsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExistsFunc([NotNull] SparqlParser.ExistsFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.existsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExistsFunc([NotNull] SparqlParser.ExistsFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.notExistsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExistsFunc([NotNull] SparqlParser.NotExistsFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.notExistsFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExistsFunc([NotNull] SparqlParser.NotExistsFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregate([NotNull] SparqlParser.AggregateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregate([NotNull] SparqlParser.AggregateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.iriOrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIriOrFunction([NotNull] SparqlParser.IriOrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.iriOrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIriOrFunction([NotNull] SparqlParser.IriOrFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.rdfLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRdfLiteral([NotNull] SparqlParser.RdfLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.rdfLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRdfLiteral([NotNull] SparqlParser.RdfLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteral([NotNull] SparqlParser.NumericLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteral([NotNull] SparqlParser.NumericLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.numericLiteralUnsigned"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralUnsigned([NotNull] SparqlParser.NumericLiteralUnsignedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.numericLiteralUnsigned"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralUnsigned([NotNull] SparqlParser.NumericLiteralUnsignedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.numericLiteralPositive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralPositive([NotNull] SparqlParser.NumericLiteralPositiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.numericLiteralPositive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralPositive([NotNull] SparqlParser.NumericLiteralPositiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.numericLiteralNegative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericLiteralNegative([NotNull] SparqlParser.NumericLiteralNegativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.numericLiteralNegative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericLiteralNegative([NotNull] SparqlParser.NumericLiteralNegativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] SparqlParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] SparqlParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] SparqlParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] SparqlParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIri([NotNull] SparqlParser.IriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.iri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIri([NotNull] SparqlParser.IriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.prefixedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixedName([NotNull] SparqlParser.PrefixedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.prefixedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixedName([NotNull] SparqlParser.PrefixedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.blankNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankNode([NotNull] SparqlParser.BlankNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.blankNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankNode([NotNull] SparqlParser.BlankNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.iriRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIriRef([NotNull] SparqlParser.IriRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.iriRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIriRef([NotNull] SparqlParser.IriRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.triplesTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplesTemplate([NotNull] SparqlParser.TriplesTemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.triplesTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplesTemplate([NotNull] SparqlParser.TriplesTemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.reifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReifier([NotNull] SparqlParser.ReifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.reifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReifier([NotNull] SparqlParser.ReifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SparqlParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] SparqlParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SparqlParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] SparqlParser.AnnotationContext context);
}
